/**
 * Regenerates src/tokens/* from the spa's design system, so marketing and the
 * app never drift. Source of truth:
 *   ../spa/app/globals.css        :root (light), .dark, @theme inline
 *   ../spa/public/logo.svg        the logo mark
 *   ../spa/app/fonts/*.woff2      Inter + Geist Mono
 *   ../spa/public/social-media-icons/*.svg
 *
 * Usage: npm run sync-tokens   (override the spa path with SPA_DIR=...)
 */
import { copyFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DERIVED } from './derived';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SPA = path.resolve(ROOT, process.env.SPA_DIR ?? '../spa');
const OUT = path.join(ROOT, 'src/tokens');

const HEADER = `GENERATED by scripts/sync-tokens.ts from spa/app/globals.css — do not edit.`;

const css = readFileSync(path.join(SPA, 'app/globals.css'), 'utf8');

/** Body of the first `selector { ... }` block (no nested braces in these). */
function block(selector: string): string {
  const start = css.indexOf(`${selector} {`);
  if (start < 0) throw new Error(`globals.css: no "${selector}" block`);
  const open = css.indexOf('{', start);
  const close = css.indexOf('\n}', open);
  return css.slice(open + 1, close);
}

function vars(body: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const m of body.replace(/\/\*[\s\S]*?\*\//g, '').matchAll(/--([\w-]+)\s*:\s*([^;]+);/g)) {
    out[m[1]] = m[2].trim();
  }
  return out;
}

const light = vars(block(':root'));
const dark = vars(block('.dark'));
const brand = light.primary;
if (!/^#[0-9a-f]{6}$/i.test(brand)) throw new Error(`unexpected light --primary: ${brand}`);

// Values that only exist in :root (e.g. --radius) apply to both themes.
for (const [k, v] of Object.entries(light)) if (!(k in dark)) dark[k] = v;

// @theme inline, verbatim except for the fonts: next/font's "Inter Fallback"
// is synthesized at Next build time and does not exist here.
let theme = block('@theme inline')
  .replace(/--font-sans:[^;]+;/, `--font-sans: 'Inter', sans-serif;`)
  .replace(/--font-mono:[^;]+;/, `--font-mono: 'Geist Mono', monospace;`);
theme += `\n  /* marketing (derived, see scripts/derived.ts) */\n  --color-brand: var(--brand);\n`;
for (const [name] of DERIVED) theme += `  --color-${name}: var(--${name});\n`;

const decl = (o: Record<string, string>) =>
  Object.entries(o).map(([k, v]) => `  --${k}: ${v};`).join('\n');
const derived = (i: 1 | 2) => DERIVED.map((d) => `  --${d[0]}: ${d[i]};`).join('\n');

writeFileSync(
  path.join(OUT, 'tokens.css'),
  `/* ${HEADER} */

:root {
${decl(light)}

  /* Brand constant: spa light --primary, used for logo + brand surfaces in BOTH themes. */
  --brand: ${brand};
${derived(1)}
}

.dark {
${decl(dark)}

  --brand: ${brand};
${derived(2)}
}

@theme inline {${theme}}
`,
);

// ── TS mirror, for SVG/inline use and the catalog ──────────────────────────
const px = (rem: string) => parseFloat(rem) * 16;
const radius = px(light.radius);

function shadows(v: Record<string, string>) {
  const x = parseFloat(v['shadow-x']), y = parseFloat(v['shadow-y']);
  const b = parseFloat(v['shadow-blur']), s = parseFloat(v['shadow-spread']);
  const o = parseFloat(v['shadow-opacity']);
  const c = (k = 1) => `color-mix(in srgb, ${v['shadow-color']} ${Math.min(100, o * 100 * k)}%, transparent)`;
  return {
    '2xs': `${x}px ${y}px ${c()}`,
    xs: `${x}px ${y}px ${b}px ${s}px ${c()}`,
    sm: `${x}px ${y}px ${b * 1.5}px ${s}px ${c()}`,
    md: `${x * 2}px ${y * 2}px ${b * 3}px ${s - 1}px ${c()}`,
    lg: `${x * 4}px ${y * 4}px ${b * 5}px ${s - 3}px ${c()}`,
    xl: `${x * 6}px ${y * 6}px ${b * 7}px ${s - 5}px ${c()}`,
    '2xl': `${x * 8}px ${y * 8}px ${Math.max(0, b * 9 - 8)}px ${s - 12}px ${c(2.5)}`,
  };
}

const colorKeys = (o: Record<string, string>) =>
  Object.fromEntries(Object.entries(o).filter(([, v]) => v.startsWith('#')));

writeFileSync(
  path.join(OUT, 'index.ts'),
  `// ${HEADER}

/** Brand violet — logo and brand surfaces, identical in light and dark. */
export const BRAND = ${JSON.stringify(brand)};

export const colors = ${JSON.stringify({ light: colorKeys(light), dark: colorKeys(dark) }, null, 2)} as const;

export type ThemeName = keyof typeof colors;
export type ColorToken = keyof typeof colors.light;

/** Tailwind radius scale, in px (from --radius). */
export const radius = ${JSON.stringify({ sm: radius - 4, md: radius - 2, lg: radius, xl: radius + 4 })} as const;

export const shadows = ${JSON.stringify({ light: shadows(light), dark: shadows(dark) }, null, 2)} as const;

export const fonts = { sans: 'Inter', mono: 'Geist Mono' } as const;
`,
);

// ── logo ──────────────────────────────────────────────────────────────────
const logo = readFileSync(path.join(SPA, 'public/logo.svg'), 'utf8');
const inner = logo.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
writeFileSync(
  path.join(OUT, 'logo.ts'),
  `// ${HEADER.replace('globals.css', 'public/logo.svg')}

/** Inner markup of the Planer mark, viewBox 0 0 40 40. */
export const LOGO_VIEWBOX = '0 0 40 40';
export const LOGO_SVG = ${JSON.stringify(inner)};
`,
);

// ── binary assets ─────────────────────────────────────────────────────────
mkdirSync(path.join(ROOT, 'public/fonts'), { recursive: true });
for (const f of ['InterVariable.woff2', 'GeistMonoVF.woff2']) {
  copyFileSync(path.join(SPA, 'app/fonts', f), path.join(ROOT, 'public/fonts', f));
}
const icons = path.join(SPA, 'public/social-media-icons');
mkdirSync(path.join(ROOT, 'public/assets/social'), { recursive: true });
for (const f of readdirSync(icons)) copyFileSync(path.join(icons, f), path.join(ROOT, 'public/assets/social', f));

console.log(
  `tokens synced from ${path.relative(ROOT, SPA)}: ${Object.keys(light).length} light / ${Object.keys(dark).length} dark vars, brand ${brand}, ${DERIVED.length} derived`,
);
